[build]
  command = "npm run build"
  publish="./build"
  base = "."

[build.environment]
  CI = "False"

# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200